name: "\U0001F41E Naturaily Storyblok Starter Bug Report"
description: Report an issue using Naturaily Storyblok Starter
labels: [pending-triage, pending-author]
body:
  - type: markdown
    attributes:
      value: |
        You're now going to fill out a bug report at the Naturaily Storyblok Starter. Thanks a lot for taking the time and let's make Starter open source projects better together!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the issue you're facing
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description so we can review it. Thanks in advance!
      placeholder: My React Naturaily Storyblok Starter configuration is ... ## Expected behavior ... ## Current Behavior ...
    validations:
      required: true
  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a link to a repo or Stackblitz that can reproduce the issue you ran into. A minimal reproduction is required, if a report is vague or has no reproduction, it will receive a "need reproduction" label.
      placeholder: Reproduction URL
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Please provide any reproduction steps that may need to be described.
      placeholder: List the commands or configuration you set when you faced the error, and describe with process you follow to get the error.
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output of `npx envinfo --system --npmPackages '{ react, @natu/*}' --binaries --browsers`
      render: shell
      placeholder: System, Binaries, Browsers, React & Storyblok SDK version
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Error logs (Optional)
      description: |
        Optional if provided reproduction. Please copy and paste the log text.
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the feature request, please make sure you do the following
      options:
        - label: Follow our [Code of Conduct](https://github.com/Naturaily/naturaily-storyblok-next-starter/blob/main/CODE_OF_CONDUCT.md)
          required: true
  - type: markdown
    attributes:
      value: |
        > This template was inspired by the [Vite issue template](https://github.com/vitejs/vite/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml)
