name: Test application generation

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  prettier-format:
    name: Prettier format
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      SKIP_ENV_VALIDATION: ${{ secrets.SKIP_ENV_VALIDATION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install
      - name: Run prettier format
        run: pnpm prettier:format

  eslint-format:
    name: Eslint format
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      SKIP_ENV_VALIDATION: ${{ secrets.SKIP_ENV_VALIDATION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install
      - name: Run eslint format
        run: pnpm eslint:format
